#!/bin/bash


function error() { cat <<< "$@" 1>&2; }

#if [ -z $1 ]; then
if [ ! $1 ]; then
	error "no dir"
	exit 1
fi

# $1 = /etc/profile.d

TARGET=/tmp/backup
#BNAME=`basename $1`
BNAME=$(basename $1)

mkdir $TARGET
tar cvzf $TARGET/$BNAME.tgz $1