#!/bin/bash

function error() { cat <<< "$@" 1>&2; }

function help_() {
	echo "Usage: $(basename $0) USER DIR TARGET"
}

function do_or_die(){
	# $1 - command, $2 - error message
	eval $1
	if [ $? -ne 0 ]; then 
		error $2
		exit $?
	fi
	}

#if [ -z $1 ]; then
if [ -z "$1" -o -z "$2" ]; then
	error "Something missing"
	help_ 
	exit 1
fi

# $1 = /etc/profile.d
# $2 = target
# $3 = timestamp

TARGET=$2
#TARGET=/tmp/backup/$USER
#BNAME=`basename $1`
BNAME=$(basename $1)
DNAME=$(dirname $1)

# 1.
#if [ ! -d $TARGET ]; then
#	mkdir $TARGET
#fi

# 2.
#if [ ! -d $TARGET ]; then;	mkdir $TARGET; fi

# 3. Правильный способ
[ -d $TARGET ] || do_or_die "mkdir -p $TARGET" "mkdir $TARGET failed"
#if [[ $? != 0 ]]...
#if [ $? -ne 0 ]; then; ... fi

#do_or_die "tar cvzf $TARGET/$BNAME_$3.tgz $1" "tar failed"
do_or_die "tar czf $TARGET/${BNAME}_${3}.tgz -C $DNAME $BNAME" "tar failed"
echo $TARGET/$BNAME